language: python
services:
  - postgresql
  - xvfb

addons:
  firefox: "60.0.1"

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.19.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - export DISPLAY=:99.0

install:
  - pip install -r requirements.txt

before_script:     
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - python manage.py test